### Read all films with File variable
@baseUrl = http://localhost:3000

GET {{baseUrl}}/films

###Read all films with a minimum duration of 160 minutes
GET {{baseUrl}}/films?minimum-duration=160

# ###Read all films that start with provided string
# GET {{baseUrl}}/films?start-with=Star&Wars

# ###Read all films ordering by budget descending
# GET {{baseUrl}}/films?order=budget

# ###Read all films ordering by budget ascending
# GET {{baseUrl}}/films?order=-budget


### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Star Wars, épisode IX : L'Ascension de Skywalker",
    "duration": 141,
    "budget": 416, 
    "link": "https://www.imdb.com/title/tt2527338/?ref_=ext_shr_lnk"
}

### Delete a film
DELETE {{baseUrl}}/films/4

### Update the film identified by 2
PATCH {{baseUrl}}/films/2
Content-Type: application/json

{
    "budget": 170
}

### Update or create the film identified by 2
PUT {{baseUrl}}/films/5
Content-Type: application/json

{
    "title":"Star Wars, épisode IX : L'Ascension de Skywalker",
    "duration": 141,
    "budget": 416, 
    "link": "https://www.imdb.com/title/tt2527338/?ref_=ext_shr_lnk"
}